### ISSUE TITLE
Wrong driver? Portal is not detected

### ISSUE THREAD

**Issue by OvercookedFish** [SigmaDolphin/SkylanderEditor#3]
I have a Skylanders Giants portal for the Wii, and every single time I attempt to connect I get the following error at the bottom of the GUI:
`Portal Not Found!`
I have tried every possible USB driver I could think of, thinking that was the issue. It wasn't. I have tried the skylanderswebdriver found online, it didn't work either. I've tried reinstalling, uninstalling, everything in relation to this device and it's driver. And still the error persists.

**Comment by OvercookedFish** [comment]
I'm on Windows 10 x64 if it makes a difference, and no the portal is not Xbox.

**Comment by OvercookedFish** [comment]
Solved, and can confirm that the drivers must be HidUSB, NOT WinUSB.

**Comment by deReeperJosh** [comment]
How did you install the HidUSB drivers @OvercookedFish? I am curious to figure out why I can only seem to install libusbk or winusb

**Comment by SigmaDolphin** [comment]
HidUSB is the default driver Windows installs when you connect a Portal
you should be able to install it with the Device Manager if you changed it

**Comment by deReeperJosh** [comment]
@SigmaDolphin I tried uninstalling and plugging the device back in but I think I may have some weird drivers on my computer as it installs LibUSBk as the driver for the device. I got it working on a different windows device that had no drivers installed however

**Comment by SigmaDolphin** [comment]
you should be able to select the default driver by the Update Driver option in the device's properties in Device Manager
you then select "Browse my computer for driver software"
then "Let me pick from a list of device drivers on my computer"
the default HidUSB driver should appear as "USB Input Device"

**Comment by deReeperJosh** [comment]
Ah okay, I'll give that a go next time I'm messing around with the portals.

**Comment by deReeperJosh** [comment]
Thanks for this, had no clue USB Input device was the same as HidUSB. Can actually use this and a couple other tools now!
