### ISSUE TITLE
modINI usage means doesn't work on Linux

### ISSUE THREAD

**Issue by JohnVeness** [SigmaDolphin/SkylanderEditor#4]
Hello. Many thanks for this app. It is great to see people still working on Skylanders reverse-engineering.

For interest, I tried running this on Linux using Mono, but it didn't work due to "System.DllNotFoundException: kernel32". It turns out this is due to using modINI which references the Windows API directly, making this somewhat less than a "pure" .NET app.

I realise that you only just changed to the .ini file from the previous database, but I wonder if you had considered moving to something even more platform neutral, like XML or JSON? Or another .ini reader that doesn't rely on Windows API calls.

Many thanks again.

**Comment by SigmaDolphin** [comment]
thanks for your suggestion, i wasn't aware modINI was so reliant on a Windows environment, i did change the database from an Access database because someone informed me it required a framework and i wanted my app to require as least external stuff as possible, i will look into using XML or JSON if that can make my app more friendly on Linux systems

**Comment by SigmaDolphin** [comment]
@JohnVeness done, changed to use an XML instead of the INI, tell me how it goes, it still has a lot of DLL calls, more specifically to read HID devices, which i cannot convert to a more native use in VB.NET because they don't exist

**Comment by JohnVeness** [comment]
That's excellent, thanks for doing that so quickly. The app now launches on Linux and displays the GUI. As you expect, it crashes (with "System.DllNotFoundException: hid.dll") if I try to connect to a portal, but I expect (I have not yet tested) that it will now at least let me open, edit and save .skd and .ske files, which is a good step forward.
