### ISSUE TITLE
How to run the Programm

### ISSUE THREAD

**Issue by raphaelbleier** [SigmaDolphin/SkylanderEditor#7]
Dear SigmaDolphine,
have to run this code or do I have to compile it in Visual Studios first?

Kind Rergards,
Githubmaster!

**Comment by SigmaDolphin** [comment]
- you can download and use the code to compile and modify it yourself, Visual Studio compiles it when you run the code (although in debug mode) so the terms are a bit interchangeable

- you can also get the release in the"Releases" section which are pre-compiled binaries if you don't want to compile them yourself and only want to use the program
